function SpotParameters = SpotParametersBrainSelect(SpotParameters, MidBrain)
%makes an selection of SpotParameters structure based on the midbrain
%SpotParameters is generated by the functions SpotDetectionSNG of SpotDetectionSliceSNG
%input can be cells with multiple values
%Warning: watch out for shifted x an y parameters
%EXAMPLE:     SpotParameters2 = SpotParametersBrainSelect(INFO.SpotParameters,MidBrain)
%
%
%{
 SpotParameters = INFO.SpotParameters
 
%}

if iscell(SpotParameters) && iscell(MidBrain)
    
    full = find(~cellfun('isempty', MidBrain));
    empty = find(cellfun('isempty', MidBrain));
    
    for k1 = full
        [spotcentroids] = reshape([SpotParameters{k1}.Centroid], 2, numel(SpotParameters{k1}))';
        [ins, ~] = inpolygon(spotcentroids(:, 1), spotcentroids(:, 2), MidBrain{k1}(:, 2), MidBrain{k1}(:, 1));
        SpotParameters{k1} = SpotParameters{k1}(ins');
    end
 if ~isempty(empty)
     for k1 = empty
     SpotParameters{k1} = [];
 
     end
 end
else
    [spotcentroids] = reshape([SpotParameters.Centroid], 2, numel(SpotParameters))';
    [ins, ~] = inpolygon(spotcentroids(:, 1), spotcentroids(:, 2), MidBrain(:, 2), MidBrain(:, 1));
    SpotParameters = SpotParameters(ins');
end